[policy]
name = "gear_sonic"

[policy.config.encoder]
model_path = "models/gear-sonic/model_encoder.onnx"
execution_provider = { type = "cpu" }
optimization_level = "extended"
num_threads = 1

[policy.config.decoder]
model_path = "models/gear-sonic/model_decoder.onnx"
execution_provider = { type = "cpu" }
optimization_level = "extended"
num_threads = 1

[policy.config.planner]
model_path = "models/gear-sonic/planner_sonic.onnx"
execution_provider = { type = "cpu" }
optimization_level = "extended"
num_threads = 1

[robot]
config_path = "configs/robots/unitree_g1.toml"

[comm]
frequency_hz = 50
topics = { joint_state = "unitree/g1/joint_state", imu = "unitree/g1/imu", joint_target_command = "unitree/g1/command/joint_position" }

[runtime]
velocity = [0.30, 0.0, 0.05]
max_ticks = 60
